version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: catalog-mysql

    environment:
      MYSQL_DATABASE: catalogdb
      MYSQL_USER: catalog
      MYSQL_PASSWORD: catalog
      MYSQL_ROOT_PASSWORD: root

    ports:
      - "3306:3306"

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: catalog-redis

    ports:
      - "6379:6379"
      -
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10